CREATE DATABASE NhaHang
GO
USE [NhaHang]
GO
/****** Object:  UserDefinedFunction [dbo].[CHECK_MONAN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[CHECK_MONAN] (@ID_MA CHAR(10))
RETURNS INT
AS
BEGIN
IF EXISTS(SELECT * FROM dbo.GOI_MON,dbo.PHIEU_YC
WHERE ID_MONAN = @ID_MA
AND TRANG_THAI LIKE 'Chua Thanh Toan')
BEGIN
RETURN 1
END
RETURN 0
END
GO
/****** Object:  UserDefinedFunction [dbo].[DN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

----THUONG
--DANG NHAP 

CREATE FUNCTION [dbo].[DN] (@kh nvarchar(30))
RETURNS @BANGTK TABLE
(MK CHAR(10),
CHUC_VU VARCHAR(20),
TEN_NV NVARCHAR(30)
)AS
BEGIN
INSERT INTO @BANGTK 
SELECT MK, CHUC_VU , TEN_NV FROM DANGNHAP, NHAN_VIEN WHERE DANGNHAP.ID_NV = NHAN_VIEN.ID_NV AND NHAN_VIEN.ID_NV = @kh
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[DOANH_THU]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[DOANH_THU]() RETURNS @TB TABLE(THANG CHAR(2),NAM CHAR(4),THU FLOAT,CHI FLOAT)
AS BEGIN
DECLARE @tb2  TABLE(THANG CHAR(2),NAM CHAR(4),THU FLOAT,CHI FLOAT)
INSERT INTO @tb2
SELECT MONTH(NGAY_TT) AS THANG,YEAR(NGAY_TT) AS NAM,THANH_TIEN,0
FROM dbo.HOA_DON

INSERT INTO @tb2
SELECT MONTH(NGAY_NHAP) AS THANG,YEAR(NGAY_NHAP) AS NAM,0,TONG_TIEN
FROM dbo.PHIEU_NHAP

INSERT INTO @TB
SELECT THANG,NAM,SUM(THU),SUM(CHI)
FROM @tb2
GROUP BY THANG,NAM
ORDER BY NAM,THANG ASC
RETURN 
END
GO
/****** Object:  UserDefinedFunction [dbo].[DOANH_THU_NGAY]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[DOANH_THU_NGAY](@nam INT) RETURNS @TB TABLE(NGAY CHAR(2),THANG CHAR(2),THU FLOAT,CHI FLOAT)
AS BEGIN

DECLARE @TB2 TABLE (ngay CHAR(2),thang CHAR(2),thu FLOAT,chi FLOAT)

INSERT INTO @TB2
SELECT DATEPART(DD,NGAY_TT) AS NGAY,MONTH(NGAY_TT) AS THANG,THANH_TIEN,0
FROM dbo.HOA_DON

INSERT INTO @TB2
SELECT DATEPART(DD,NGAY_NHAP) AS NGAY,MONTH(NGAY_NHAP) AS THANG,0,TONG_TIEN
FROM dbo.PHIEU_NHAP

INSERT INTO @TB
SELECT ngay,thang,SUM(thu),SUM(chi)
FROM @TB2
GROUP BY ngay,thang

RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[DOANH_THU_NGAY2]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[DOANH_THU_NGAY2](@nam INT) RETURNS @TB TABLE(NGAY CHAR(2),THANG CHAR(2),THU FLOAT,CHI FLOAT)
AS BEGIN

DECLARE @TB2 TABLE (ngay CHAR(2),thang CHAR(2),thu FLOAT,chi FLOAT)

INSERT INTO @TB2
SELECT DATEPART(DD,NGAY_TT) AS NGAY,MONTH(NGAY_TT) AS THANG,THANH_TIEN,0
FROM dbo.HOA_DON

INSERT INTO @TB2
SELECT DATEPART(DD,NGAY_NHAP) AS NGAY,MONTH(NGAY_NHAP) AS THANG,0,TONG_TIEN
FROM dbo.PHIEU_NHAP

INSERT INTO @TB
SELECT ngay,thang,SUM(thu),SUM(chi)
FROM @TB2
GROUP BY ngay,thang

RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[FC_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Thong ke khach hang

CREATE FUNCTION [dbo].[FC_KH] 
(@NAM CHAR(10))
RETURNS @BANGTK TABLE
(thang INT,
sophieu INT)AS
BEGIN
INSERT INTO @BANGTK SELECT (MONTH(NGAY)) as thang, COUNT(ID_PHIEU) FROM KHACH_HANG, PHIEU_YC where KHACH_HANG.ID_KH = PHIEU_YC.ID_KH AND YEAR(NGAY) = @nam GROUP BY MONTH(NGAY) ORDER BY thang ASC
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[KT_KM]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[KT_KM](@ngaytt DATE) RETURNS 
@bangkm TABLE ( ID_KM CHAR(10),
				PHAN_TRAM_GIAM FLOAT,
				NGAY_BD DATE,
				NGAY_KT DATE
) AS
BEGIN
	INSERT INTO @bangkm
	SELECT ID_KM,PHAN_TRAM_GIAM,NGAY_BD,NGAY_KT FROM dbo.KHUYEN_MAI
	WHERE @ngaytt BETWEEN NGAY_BD AND NGAY_KT
	OR ID_KM = 'KM1000'
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[KT_SL]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--GIOI HAN SO LUONG XUAT
CREATE FUNCTION [dbo].[KT_SL]
(@tennl varchar(20)
) RETURNS INT
AS BEGIN
DECLARE @ID_NL INT
IF(not exists (select * from nguyen_lieu where ten_nl = @tennl)) return -1
SELECT @ID_NL=SO_LUONG FROM NGUYEN_LIEU WHERE TEN_NL = @tennl
RETURN @ID_NL
END
GO
/****** Object:  UserDefinedFunction [dbo].[LUONG_KHACH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[LUONG_KHACH]() RETURNS @TB TABLE(THANG CHAR(2),NAM CHAR(4),LUONG_KHACH INT)
AS BEGIN
INSERT INTO @TB
SELECT MONTH(dbo.PHIEU_YC.NGAY),YEAR(dbo.PHIEU_YC.NGAY),COUNT(dbo.PHIEU_YC.ID_KH)
FROM dbo.PHIEU_YC
GROUP BY MONTH(dbo.PHIEU_YC.NGAY),YEAR(dbo.PHIEU_YC.NGAY)
RETURN 
END

GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_HD]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[NEW_ID_HD]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_ADD CHAR(20) = (SELECT TOP 1 ID_PHIEU 
FROM dbo.HOA_DON ORDER BY ID_HD DESC)
RETURN (SELECT 'HD' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),4,8))+1)))
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_INPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--TU DONG TANG ID INPUT
CREATE FUNCTION [dbo].[NEW_ID_INPUT]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_NL CHAR(10)
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_NHAP FROM dbo.PHIEU_NHAP ORDER BY ID_NHAP DESC)
SET @ID_NL =  'PN' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),3,8))+1))
RETURN @ID_NL
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
----KHACH_HANG

--TU DONG TANG ID
CREATE FUNCTION [dbo].[NEW_ID_KH]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_KH FROM dbo.KHACH_HANG ORDER BY ID_KH DESC )
RETURN (SELECT 'KH' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),3,8))+1)))
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_KM]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[NEW_ID_KM]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_ADD CHAR(20) = (SELECT TOP 1 ID_KM
FROM dbo.KHUYEN_MAI ORDER BY ID_KM DESC)
RETURN (SELECT 'KM' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),4,8))+1001)))
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_MONAN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[NEW_ID_MONAN]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_MONAN FROM dbo.MON_AN ORDER BY ID_MONAN DESC)
RETURN (SELECT 'MA' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),3,8))+1)))
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_NCC]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[NEW_ID_NCC]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_NHACC FROM dbo.NHA_CC ORDER BY ID_NHACC DESC )
RETURN (SELECT 'NCC' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),4,9))+1)))
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_NL]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--TU DONG TANG ID NGUYEN LIEU NEU NHAP NGUYEN LIEU MOI
CREATE FUNCTION [dbo].[NEW_ID_NL]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_NL CHAR(10)
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_NL FROM dbo.NGUYEN_LIEU ORDER BY ID_NL DESC)
SET @ID_NL =  'NL' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),3,8))+1))
RETURN @ID_NL
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_NV]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



----NHAN_VIEN
--TU DONG TANG ID
CREATE FUNCTION [dbo].[NEW_ID_NV]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_NV FROM dbo.NHAN_VIEN ORDER BY ID_NV DESC )
RETURN (SELECT 'NV' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),3,8))+1)))
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_OUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--TU DONG TANG ID INPUT
CREATE FUNCTION [dbo].[NEW_ID_OUTPUT]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_NL CHAR(10)
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_XUAT FROM dbo.PHIEU_XUAT ORDER BY ID_XUAT DESC)
SET @ID_NL =  'PX' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),3,8))+1))
RETURN @ID_NL
END
GO
/****** Object:  UserDefinedFunction [dbo].[NEW_ID_PYC]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[NEW_ID_PYC]() RETURNS CHAR(10)
AS BEGIN
DECLARE @ID_NL CHAR(10)
DECLARE @ID_ADD CHAR(10) = (SELECT TOP 1 ID_PHIEU FROM dbo.PHIEU_YC ORDER BY ID_PHIEU DESC)
SET @ID_NL =  'PYC' + CONVERT(CHAR(10),(CONVERT(INT,SUBSTRING((@ID_ADD),4,8))+1))
RETURN @ID_NL
END
GO
/****** Object:  UserDefinedFunction [dbo].[PL_DETAILINPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--DETAIL INPUT
--LOAD FORM
CREATE FUNCTION [dbo].[PL_DETAILINPUT] 
(@ID CHAR(10))
RETURNS @BANGTK TABLE
(TEN_NL VARCHAR(10),
SOLUONG INT,
DON_GIA FLOAT,
TONG_GIA FLOAT
)AS
BEGIN
INSERT INTO @BANGTK SELECT TEN_NL, SOLUONG, DON_GIA, (NHAP_NL.SOLUONG*DON_GIA) AS TONG_GIA FROM NHAP_NL, NGUYEN_LIEU WHERE NHAP_NL.ID_NL=NGUYEN_LIEU.ID_NL AND NHAP_NL.ID_NHAP = @ID
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[PL_DETAILOUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--DETAIL OUTPUT
--LOAD FORM DETAIL OUPUT
CREATE FUNCTION [dbo].[PL_DETAILOUTPUT] 
(@ID CHAR(10))
RETURNS @BANGTK TABLE
(TEN_NL VARCHAR(10),
SO_LUONG INT,
DON_GIA FLOAT,
TONG_GIA FLOAT
)AS
BEGIN
INSERT INTO @BANGTK SELECT TEN_NL, XUAT_NL.SO_LUONG, DON_GIA, (XUAT_NL.SO_LUONG*DON_GIA) AS TONG_GIA FROM XUAT_NL, NGUYEN_LIEU WHERE XUAT_NL.ID_NL=NGUYEN_LIEU.ID_NL AND XUAT_NL.ID_XUAT = @ID
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[PL_INPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--STORAGEINPUT-------
--LOAD INPUT
CREATE FUNCTION [dbo].[PL_INPUT] 
()
RETURNS @BANGTK TABLE
(ID_NHAP CHAR(10),
NGAY_NHAP DATE,
TONG_TIEN FLOAT,
NHACC VARCHAR(20),
TEN_NV VARCHAR(20)
)AS
BEGIN
INSERT INTO @BANGTK SELECT  ID_NHAP, NGAY_NHAP,TONG_TIEN, NHACC, TEN_NV FROM PHIEU_NHAP, NHAN_VIEN, NHA_CC WHERE PHIEU_NHAP.ID_NHACC=NHA_CC.ID_NHACC AND NHAN_VIEN.ID_NV = PHIEU_NHAP.ID_NV 
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[PL_OUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--STORAGE OUTPUT
--LOAD OUPUT
CREATE FUNCTION [dbo].[PL_OUTPUT] 
()
RETURNS @BANGTK TABLE
(ID_XUAT CHAR(10),
NGAY_XUAT DATE,
TONG_TIEN FLOAT,
TEN_NV VARCHAR(20)
)AS
BEGIN
INSERT INTO @BANGTK SELECT ID_XUAT, NGAY_XUAT,TONG_TIEN, TEN_NV FROM PHIEU_XUAT, NHAN_VIEN WHERE NHAN_VIEN.ID_NV = PHIEU_XUAT.ID_NV
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[TIEU_THU]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[TIEU_THU]() RETURNS @TB TABLE(ma_monan CHAR(10),ten_monan NVARCHAR(25),loai_mon NVARCHAR(15),gia FLOAT ,tieu_thu INT)
AS BEGIN
INSERT INTO @TB
SELECT MON_AN.ID_MONAN,TEN_MONAN,TEN_LOAIMON,DON_GIA,SUM(SOLUONG)
FROM dbo.MON_AN,dbo.GOI_MON,dbo.LOAI_MON
WHERE dbo.MON_AN.ID_MONAN = dbo.GOI_MON.ID_MONAN
AND dbo.LOAI_MON.ID_LOAIMON = dbo.MON_AN.ID_LOAIMON
GROUP BY  MON_AN.ID_MONAN,TEN_MONAN,TEN_LOAIMON,DON_GIA
ORDER BY SUM(SOLUONG) DESC
 
INSERT INTO @TB

SELECT dbo.MON_AN.ID_MONAN,TEN_MONAN,TEN_LOAIMON,DON_GIA,0
FROM dbo.MON_AN,dbo.LOAI_MON
WHERE dbo.MON_AN.ID_LOAIMON =dbo.LOAI_MON.ID_LOAIMON
AND dbo.MON_AN.ID_MONAN != ALL(SELECT ID_MONAN FROM dbo.GOI_MON)

RETURN 
END

GO
/****** Object:  UserDefinedFunction [dbo].[Tim_HD]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create FUNCTION [dbo].[Tim_HD] (@kh nvarchar(30))
RETURNS @BANGTK TABLE
(ID_HD CHAR(10),
NGAY_TT date,
THANH_TIEN FLOAT, 
ID_PHIEU CHAR(10),
ID_KM CHAR(10),
ID_NV CHAR(10)
)AS
BEGIN
INSERT INTO @BANGTK 
SELECT * from dbo.HOA_DON 
WHERE ID_HD LIKE TRIM(CONCAT('%',@kh,'%')) OR ID_PHIEU LIKE TRIM(CONCAT('%',@kh,'%')) OR ID_KM LIKE TRIM(CONCAT('%',@kh,'%'))
OR THANH_TIEN LIKE TRIM(CONCAT('%',@kh,'%')) OR NGAY_TT LIKE TRIM(CONCAT('%',@kh,'%')) OR ID_NV LIKE TRIM(CONCAT('%',@kh,'%'))
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[Tim_KM]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[Tim_KM] (@km nvarchar(10))
RETURNS @BANGTK TABLE
(ID_KM CHAR(10),
PHAN_TRAM_GIAM NVARCHAR(30),
NGAY_BD date, 
NGAY_KT date
)AS
BEGIN
INSERT INTO @BANGTK 
select * from dbo.KHUYEN_MAI where ID_KM LIKE TRIM(CONCAT('%',@km,'%')) OR PHAN_TRAM_GIAM LIKE TRIM(CONCAT('%',@km,'%')) OR NGAY_BD LIKE TRIM(CONCAT('%',@km,'%')) OR NGAY_KT LIKE TRIM(CONCAT('%',@km,'%'))  
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[TimKiem_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--Tim kiem khach hang
CREATE FUNCTION [dbo].[TimKiem_KH] (@kh nvarchar(30))
RETURNS @BANGTK TABLE
(ID_KH CHAR(10),
TEN_KH NVARCHAR(30),
SDT NVARCHAR(20), 
GIOI_TINH VARCHAR(10),
DIA_CHI NVARCHAR(30)
)AS
BEGIN
INSERT INTO @BANGTK 
select * from KHACH_HANG where ID_KH LIKE TRIM(CONCAT('%',@kh,'%')) OR TEN_KH LIKE TRIM(CONCAT('%',@kh,'%')) OR DIA_CHI LIKE TRIM(CONCAT('%',@kh,'%')) OR SDT LIKE TRIM(CONCAT('%',@kh,'%')) OR GIOI_TINH LIKE TRIM(CONCAT('%',@kh,'%')) 
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[TimKiem_NCC]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--NHA CC
CREATE FUNCTION [dbo].[TimKiem_NCC] (@kh nvarchar(30))
RETURNS @BANGTK TABLE
(ID_NHACC CHAR(10),
NHACC NVARCHAR(30),
SDT NVARCHAR(20), 
DIA_CHI NVARCHAR(30)
)AS
BEGIN
INSERT INTO @BANGTK 
select * from NHA_CC where ID_NHACC LIKE TRIM(CONCAT('%',@kh,'%')) OR NHACC LIKE TRIM(CONCAT('%',@kh,'%')) OR SDT LIKE TRIM(CONCAT('%',@kh,'%')) OR DIA_CHI LIKE TRIM(CONCAT('%',@kh,'%'))
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[TimKiem_NL]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--STORAGE
--TIM KIEM
CREATE FUNCTION [dbo].[TimKiem_NL] (@kh nvarchar(30))
RETURNS @BANGTK TABLE
(ID_NL CHAR(10),
TEN_NL NVARCHAR(30),
SO_LUONG INT

)AS
BEGIN
INSERT INTO @BANGTK 
select * from NGUYEN_LIEU where TEN_NL like TRIM(CONCAT('%',@kh,'%')) OR ID_NL LIKE TRIM(CONCAT('%',@kh,'%')) OR SO_LUONG LIKE TRIM(CONCAT('%',@kh,'%'))
RETURN
END
GO
/****** Object:  UserDefinedFunction [dbo].[TimKiem_NV]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--Tim kiem nhan vien
CREATE FUNCTION [dbo].[TimKiem_NV] (@kh nvarchar(30))
RETURNS @BANGTK TABLE
(ID_NV CHAR(10),
TEN_NV NVARCHAR(30),
GIOI_TINH VARCHAR(10),
NGAY_SINH DATE,
SDT NVARCHAR(20),
CHUC_VU VARCHAR(20),
DIA_CHI NVARCHAR(30),
LUONG FLOAT

)AS
BEGIN
INSERT INTO @BANGTK 
select * from NHAN_VIEN where TEN_NV LIKE TRIM(CONCAT('%',@kh,'%')) OR ID_NV LIKE TRIM(CONCAT('%',@kh,'%')) OR GIOI_TINH LIKE TRIM(CONCAT('%',@kh,'%')) OR NGAY_SINH LIKE TRIM(CONCAT('%',@kh,'%')) OR SDT LIKE TRIM(CONCAT('%',@kh,'%')) OR CHUC_VU LIKE TRIM(CONCAT('%',@kh,'%')) OR LUONG LIKE TRIM(CONCAT('%',@kh,'%')) OR DIA_CHI LIKE TRIM(CONCAT('%',@kh,'%'))
RETURN
END
GO
/****** Object:  Table [dbo].[BAN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAN](
	[ID_BAN] [char](10) NOT NULL,
	[TRANG_THAI] [nchar](20) NULL,
	[SOGHE] [int] NULL,
	[ID_PHIEU] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_BAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DANGNHAP]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DANGNHAP](
	[ID_NV] [char](10) NOT NULL,
	[MK] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GOI_MON]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GOI_MON](
	[SOLUONG] [int] NULL,
	[ID_PHIEU] [char](10) NOT NULL,
	[ID_MONAN] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PHIEU] ASC,
	[ID_MONAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOA_DON]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOA_DON](
	[ID_HD] [char](10) NOT NULL,
	[NGAY_TT] [date] NULL,
	[THANH_TIEN] [float] NULL,
	[ID_PHIEU] [char](10) NULL,
	[ID_KM] [char](10) NULL,
	[ID_NV] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_HD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH_HANG]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG](
	[ID_KH] [char](10) NOT NULL,
	[TEN_KH] [nvarchar](45) NULL,
	[SDT] [varchar](12) NULL,
	[GIOI_TINH] [varchar](5) NULL,
	[DIA_CHI] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_KH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHUYEN_MAI]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHUYEN_MAI](
	[ID_KM] [char](10) NOT NULL,
	[PHAN_TRAM_GIAM] [float] NULL,
	[NGAY_BD] [date] NULL,
	[NGAY_KT] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_KM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAI_MON]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAI_MON](
	[ID_LOAIMON] [char](10) NOT NULL,
	[TEN_LOAIMON] [nvarchar](45) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_LOAIMON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MON_AN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MON_AN](
	[ID_MONAN] [char](10) NOT NULL,
	[TEN_MONAN] [nvarchar](50) NULL,
	[DON_GIA] [float] NULL,
	[ID_LOAIMON] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MONAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NGUYEN_LIEU]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUYEN_LIEU](
	[ID_NL] [char](10) NOT NULL,
	[TEN_NL] [nvarchar](45) NULL,
	[SO_LUONG] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHA_CC]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHA_CC](
	[ID_NHACC] [char](10) NOT NULL,
	[NHACC] [nvarchar](45) NULL,
	[DIA_CHI] [nvarchar](100) NULL,
	[SDT] [varchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NHACC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAN_VIEN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAN_VIEN](
	[ID_NV] [char](10) NOT NULL,
	[TEN_NV] [nvarchar](45) NULL,
	[GIOI_TINH] [nchar](5) NULL,
	[NGAY_SINH] [date] NULL,
	[SDT] [varchar](12) NULL,
	[CHUC_VU] [varchar](45) NULL,
	[DIA_CHI] [nvarchar](100) NULL,
	[LUONG] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAP_NL]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAP_NL](
	[ID_NL] [char](10) NOT NULL,
	[ID_NHAP] [char](10) NOT NULL,
	[SOLUONG] [int] NULL,
	[DON_GIA] [float] NULL,
	[TONG_GIA] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NL] ASC,
	[ID_NHAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEU_NHAP]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEU_NHAP](
	[ID_NHAP] [char](10) NOT NULL,
	[NGAY_NHAP] [date] NULL,
	[TONG_TIEN] [float] NULL,
	[ID_NHACC] [char](10) NULL,
	[ID_NV] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NHAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEU_XUAT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEU_XUAT](
	[ID_XUAT] [char](10) NOT NULL,
	[NGAY_XUAT] [date] NULL,
	[TONG_TIEN] [float] NULL,
	[ID_NV] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_XUAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEU_YC]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEU_YC](
	[ID_PHIEU] [char](10) NOT NULL,
	[NGAY] [date] NULL,
	[TRANG_THAI] [nvarchar](15) NULL,
	[ID_KH] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PHIEU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[XUAT_NL]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[XUAT_NL](
	[ID_NL] [char](10) NOT NULL,
	[ID_XUAT] [char](10) NOT NULL,
	[SO_LUONG] [int] NULL,
	[DON_GIA] [float] NULL,
	[TONG_GIA] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NL] ASC,
	[ID_XUAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1001     ', N'Da Dat              ', 6, N'PYC1024   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1002     ', N'Da Dat              ', 8, N'PYC1025   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1003     ', N'Da Dat              ', 6, N'PYC1025   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1004     ', N'Chua Dat            ', 8, NULL)
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1005     ', N'Chua Dat            ', 8, NULL)
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1006     ', N'Da Dat              ', 6, N'PYC1028   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1007     ', N'Chua Dat            ', 8, NULL)
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1008     ', N'Day                 ', 6, N'PYC1026   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1009     ', N'Chua Dat            ', 6, NULL)
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1010     ', N'Chua Dat            ', 8, NULL)
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1011     ', N'Chua Dat            ', 8, NULL)
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1012     ', N'Day                 ', 6, N'PYC1026   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1013     ', N'Da Dat              ', 6, N'PYC1027   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1014     ', N'Da Dat              ', 8, N'PYC1027   ')
GO
INSERT [dbo].[BAN] ([ID_BAN], [TRANG_THAI], [SOGHE], [ID_PHIEU]) VALUES (N'B1015     ', N'Chua Dat            ', 6, NULL)
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1001    ', N'1         ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1002    ', N'HI        ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1003    ', N'k         ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1004    ', N'NV        ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1005    ', N'NV1005    ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1006    ', N'NV1006    ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1007    ', N'NV1007    ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1008    ', N'NV1008    ')
GO
INSERT [dbo].[DANGNHAP] ([ID_NV], [MK]) VALUES (N'NV1009    ', N'NV1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1001   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1001   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1001   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1001   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1001   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1001   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1001   ', N'MA3007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1001   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1002   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1002   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1002   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1002   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1002   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1002   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1002   ', N'MA3007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1002   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1003   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1003   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1003   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1003   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1003   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1003   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (8, N'PYC1003   ', N'MA3007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1003   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1004   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1004   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1004   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1004   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1004   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1004   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (7, N'PYC1004   ', N'MA3007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1004   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1005   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (7, N'PYC1005   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1005   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1005   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (7, N'PYC1005   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1005   ', N'MA3004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1005   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1006   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1006   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1006   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1006   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1006   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1006   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1006   ', N'MA3007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1006   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (7, N'PYC1007   ', N'MA1001    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (7, N'PYC1007   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (8, N'PYC1007   ', N'MA2003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (8, N'PYC1007   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1007   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (6, N'PYC1007   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1007   ', N'MA3007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1007   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA1005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA1008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1009   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA1010    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA2006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA2007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA4003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1009   ', N'MA4004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1009   ', N'MA4005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1010   ', N'MA1008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (4, N'PYC1010   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1010   ', N'MA1010    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1010   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1011   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1011   ', N'MA1003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1011   ', N'MA1004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1012   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1012   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1012   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1012   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1012   ', N'MA1010    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1012   ', N'MA4004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1012   ', N'MA4005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (5, N'PYC1012   ', N'MA4007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1015   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1015   ', N'MA1003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA1004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1015   ', N'MA1005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1015   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1015   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA1008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1015   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA2004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA2005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA2006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA2007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA3005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA3006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1015   ', N'MA3009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1016   ', N'MA1004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1016   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1016   ', N'MA3008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1017   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1017   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1017   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1017   ', N'MA1010    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1018   ', N'MA1003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1018   ', N'MA1004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1018   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1019   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1019   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1019   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1019   ', N'MA1010    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1020   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1020   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1020   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1020   ', N'MA1010    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1021   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1021   ', N'MA1003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1021   ', N'MA1004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1022   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1023   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1023   ', N'MA1003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1023   ', N'MA1004    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (3, N'PYC1023   ', N'MA1005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1023   ', N'MA1006    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1023   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1024   ', N'MA4005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1024   ', N'MA4007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1025   ', N'MA1002    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1025   ', N'MA1003    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1025   ', N'MA1005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1025   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1026   ', N'MA1005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1026   ', N'MA1008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1026   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1027   ', N'MA1005    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1027   ', N'MA1008    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (2, N'PYC1027   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1028   ', N'MA1007    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1028   ', N'MA1009    ')
GO
INSERT [dbo].[GOI_MON] ([SOLUONG], [ID_PHIEU], [ID_MONAN]) VALUES (1, N'PYC1028   ', N'MA1010    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1001    ', CAST(N'2021-04-10' AS Date), 987, N'PYC1001   ', N'KM1005    ', N'NV1003    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1002    ', CAST(N'2021-03-20' AS Date), 800, N'PYC1002   ', N'KM1003    ', N'NV1002    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1003    ', CAST(N'2021-02-01' AS Date), 880, N'PYC1003   ', N'KM1006    ', N'NV1002    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1004    ', CAST(N'2021-07-10' AS Date), 30.5, N'PYC1004   ', N'KM1007    ', N'NV1004    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1005    ', CAST(N'2020-02-12' AS Date), 450, N'PYC1005   ', N'KM1008    ', N'NV1005    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1006    ', CAST(N'2021-07-30' AS Date), 30.5, N'PYC1006   ', N'KM1007    ', N'NV1007    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1007    ', CAST(N'2021-08-10' AS Date), 30.5, N'PYC1007   ', N'KM1002    ', N'NV1003    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1009    ', CAST(N'2021-06-16' AS Date), 689, N'PYC1009   ', N'KM1000    ', N'NV1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1010    ', CAST(N'2021-06-17' AS Date), 96, N'PYC1010   ', N'KM1009    ', N'nv1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1011    ', CAST(N'2021-06-17' AS Date), 652.8, N'PYC1011   ', N'KM1006    ', N'NV1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1012    ', CAST(N'2021-07-01' AS Date), 1625.4, N'PYC1012   ', N'KM1006    ', N'NV1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1015    ', CAST(N'2021-06-16' AS Date), 493.2, N'PYC1015   ', N'KM1003    ', N'NV1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1017    ', CAST(N'2021-06-17' AS Date), 181, N'PYC1017   ', N'KM1006    ', N'NV1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1018    ', CAST(N'2021-08-01' AS Date), 1000, N'PYC1018   ', N'KM1000    ', N'nv1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1019    ', CAST(N'2021-09-17' AS Date), 500, N'PYC1019   ', N'KM1000    ', N'nv1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1020    ', CAST(N'2021-06-17' AS Date), 48, N'PYC1020   ', N'KM1009    ', N'NV1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1021    ', CAST(N'2021-06-17' AS Date), 161, N'PYC1021   ', N'KM1009    ', N'nv1001    ')
GO
INSERT [dbo].[HOA_DON] ([ID_HD], [NGAY_TT], [THANH_TIEN], [ID_PHIEU], [ID_KM], [ID_NV]) VALUES (N'HD1022    ', CAST(N'2021-06-17' AS Date), 37, N'PYC1022   ', N'KM1009    ', N'nv1001    ')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1001    ', N'Nguyen Huy Tuan', N'0963403400', N'Nam', N'Ha Noi')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1002    ', N'Bui Thi Thoa', N'4523454545', N'Nu', N'Hoa Binh')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1003    ', N'Nguyen Vinh Nhat', N'234245450', N'Nam', N'Nghe An')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1004    ', N'Bui Huy Hoang', N'0934234200', N'Nam', N'Nghe An')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1005    ', N'Do Minh Hieu', N'0963402340', N'Nam', N'Ha Noi')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1006    ', N'Thai Doan Sang', N'0123403400', N'Nam', N'Nghe An')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1007    ', N'Dang Thi Thuong', N'0345403400', N'Nu', N'Thanh Hoa')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1008    ', N'Vu Thi Ngoc Anh', N'0234403400', N'Nu', N'Gia Lai')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1009    ', N'Thach Thi Nuong', N'0111403400', N'Nu', N'Thanh Hoa')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1010    ', N'Trieu Thuy Hang', N'0232303400', N'Nu', N'Ninh Binh')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1011    ', N'Ho Anh Dung', N'0934533400', N'Nam', N'Nghe An')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1012    ', N'Nguyen Thi Hang', N'0213303400', N'Nu', N'Nghe An')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1013    ', N'Chu Thi Linh', N'0923403400', N'Nu', N'Nghe An')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1014    ', N'Nguyen Thi Thuy', N'021234400', N'Nu', N'Hai Duong')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1015    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1016    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1017    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1018    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1019    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1020    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1021    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1022    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1023    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1024    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1025    ', N'', N'', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1026    ', N'Le Quang Long', N'0832008663', N'Nu', N'Dong Da')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1027    ', N'', N'746534884709', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1028    ', N'', N'123456', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1029    ', N'', N'63547612534', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1030    ', N'', N'1233', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1031    ', N'jjbjnjn', N'12345', N'Nam', N'nv')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1032    ', N'', N'23412341233', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1033    ', N'234ydfyy', N'63746526343', N'Nam', N'dfjgfdjd')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1034    ', N'', N'001122', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1035    ', N'', N'0240010', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1036    ', N'', N'0123456', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1037    ', N'', N'00112233', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1038    ', N'', N'11223344', N'', N'')
GO
INSERT [dbo].[KHACH_HANG] ([ID_KH], [TEN_KH], [SDT], [GIOI_TINH], [DIA_CHI]) VALUES (N'KH1039    ', N'', N'25342365665', N'', N'')
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1000    ', 0, NULL, NULL)
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1001    ', 0.3, CAST(N'2021-01-01' AS Date), CAST(N'2021-01-02' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1002    ', 0.1, CAST(N'2021-10-09' AS Date), CAST(N'2021-10-29' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1003    ', 0.2, CAST(N'2021-06-01' AS Date), CAST(N'2021-07-01' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1004    ', 0.3, CAST(N'2021-10-08' AS Date), CAST(N'2021-10-27' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1005    ', 0.2, CAST(N'2021-10-07' AS Date), CAST(N'2021-10-27' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1006    ', 0.5, CAST(N'2021-06-06' AS Date), CAST(N'2021-06-25' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1007    ', 0.2, CAST(N'2021-10-20' AS Date), CAST(N'2021-11-29' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1008    ', 0.5, CAST(N'2021-10-29' AS Date), CAST(N'2021-11-29' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1009    ', 0.6, CAST(N'2021-06-10' AS Date), CAST(N'2021-06-20' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1010    ', 0.3, CAST(N'2021-05-01' AS Date), CAST(N'2021-07-01' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1011    ', 0.1, CAST(N'2021-09-11' AS Date), CAST(N'2021-12-31' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1012    ', 0.3, CAST(N'2021-09-11' AS Date), CAST(N'2021-12-30' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1013    ', 0.2, CAST(N'2021-04-16' AS Date), CAST(N'2021-07-16' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1014    ', 0.3, CAST(N'2021-04-15' AS Date), CAST(N'2021-12-08' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1015    ', 0.4, CAST(N'2021-01-05' AS Date), CAST(N'2021-12-07' AS Date))
GO
INSERT [dbo].[KHUYEN_MAI] ([ID_KM], [PHAN_TRAM_GIAM], [NGAY_BD], [NGAY_KT]) VALUES (N'KM1016    ', 0.4, CAST(N'2021-01-02' AS Date), CAST(N'2021-05-12' AS Date))
GO
INSERT [dbo].[LOAI_MON] ([ID_LOAIMON], [TEN_LOAIMON]) VALUES (N'LM1001    ', N'Foods')
GO
INSERT [dbo].[LOAI_MON] ([ID_LOAIMON], [TEN_LOAIMON]) VALUES (N'LM1002    ', N'Drinks')
GO
INSERT [dbo].[LOAI_MON] ([ID_LOAIMON], [TEN_LOAIMON]) VALUES (N'LM1003    ', N'Snacks')
GO
INSERT [dbo].[LOAI_MON] ([ID_LOAIMON], [TEN_LOAIMON]) VALUES (N'LM1004    ', N'Dessert')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1001    ', N'Bánh Đa', 30.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1002    ', N'Bánh Khọt', 50, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1003    ', N'Bún Bò Huế', 30.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1004    ', N'Cháo Bồ Câu', 29.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1005    ', N'Cơm Cháy', 30.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1006    ', N'Cơm Tấm', 29.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1007    ', N'Gỏi Cuốn', 30.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1008    ', N'Mì Quảng', 29.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1009    ', N'Miến Lươn', 30.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA1010    ', N'Phở Bò', 29.5, N'LM1001    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2001    ', N'Bia Heineken', 20.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2003    ', N'Cô Ca', 20.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2004    ', N'Nước Dừa', 30.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2005    ', N'Rượu Vang', 20.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2006    ', N'Sinh Tố Bơ', 30.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2007    ', N'Sinh Tố Dâu', 20.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA2008    ', N'Sinh Tố Đu Đủ', 30.5, N'LM1002    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3001    ', N'Bắp Ngô', 31.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3002    ', N'Bí Đỏ', 30.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3003    ', N'Hành Tây', 31.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3004    ', N'Khoai Tây', 31.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3005    ', N'Mực Ống', 30.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3006    ', N'Phô Mai', 31.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3007    ', N'Tôm Cay', 30.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3008    ', N'Gà Nướng', 31.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3009    ', N'Tôm Miếng', 30.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA3010    ', N'Ngô Giòn', 30.5, N'LM1003    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4001    ', N'Bánh Bông Lan', 31.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4002    ', N'Bánh Chuối Nướng', 30.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4003    ', N'Bánh Đậu Xanh', 31.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4004    ', N'Bánh Trôi Tàu', 30.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4005    ', N'Chè Cốm', 31.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4007    ', N'Chè Trái Cây', 31.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4008    ', N'Tào Phớ', 30.5, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4011    ', N'Bánh Bèo', 15, N'LM1004    ')
GO
INSERT [dbo].[MON_AN] ([ID_MONAN], [TEN_MONAN], [DON_GIA], [ID_LOAIMON]) VALUES (N'MA4012    ', N'Món ăn đã sửa', 50, N'LM1001    ')
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1001    ', N'Hanh', 10000)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1002    ', N'Tom', 200)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1003    ', N'Thit Bo', 200)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1004    ', N'Ga', 200)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1005    ', N'Thit Lon', 200)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1006    ', N'Thit BaBa', 150)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1007    ', N'Thit Be', 200)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1008    ', N'Ot', 1000)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1009    ', N'Xa', 2000)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1010    ', N'Xuc Xich', 0)
GO
INSERT [dbo].[NGUYEN_LIEU] ([ID_NL], [TEN_NL], [SO_LUONG]) VALUES (N'NL1011    ', N'Cam', 0)
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1001   ', N'CT Hong Phu A', N'Ha Noi', N'036546354')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1002   ', N'CT Thuc Pham', N'Phu Tho', N'076253563')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1003   ', N'CT Bich Chi', N'Hai Duong', N'027651261')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1004   ', N'CT Thai Duong', N'Nam Dinh', N'056345632')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1005   ', N'CT Phu My', N'Ha Noi', N'034635463')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1006   ', N'CT Tien Phat', N'Nam Dinh', N'027463647')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1007   ', N'CT Hoang Long', N'Ha Noi', N'073647687')
GO
INSERT [dbo].[NHA_CC] ([ID_NHACC], [NHACC], [DIA_CHI], [SDT]) VALUES (N'NCC1008   ', N'CT Hong Phu A', N'Ha Noi', N'036546354')
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1001    ', N'Đỗ Thị Mai Hường', N'Nu   ', CAST(N'2000-02-02' AS Date), N'094566453', N'Quan Ly', N'Nghe An', 1000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1002    ', N'Ha Manh Duy', N'Nam  ', CAST(N'2000-01-02' AS Date), N'098734455', N'Quan Ly', N'Ha Nam', 1000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1003    ', N'Nguyen Minh Hieu', N'Nam  ', CAST(N'2000-11-08' AS Date), N'032654342', N'Nhan Vien', N'Vinh Yen', 1000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1004    ', N'Pham Dang Quang', N'Nam  ', CAST(N'2000-04-20' AS Date), N'047563456', N'Nhan Vien', N'Hoa Binh', 2000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1005    ', N'Nguyen Thao Nguye', N'Nu   ', CAST(N'2000-07-16' AS Date), N'034564765', N'Nhan Vien', N'Ha Noi', 2000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1006    ', N'Nguyen Tuan Anh', N'Nam  ', CAST(N'2000-02-02' AS Date), N'054475677', N'Nhan Vien', N'Bac Ninh', 1000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1007    ', N'Nguyen Thi Lien', N'Nu   ', CAST(N'2000-02-27' AS Date), N'073647357', N'Nhan Vien', N'Ninh Binh', 1000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1008    ', N'Nguyen Thi Van', N'Nu   ', CAST(N'2000-06-02' AS Date), N'072325325', N'Nhan Vien', N'Nam Dinh', 1000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1009    ', N'Bui Thi Thoa', N'Nu   ', CAST(N'2000-04-22' AS Date), N'023762732', N'Nhan Vien', N'Hoa Binh', 3000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1010    ', N'Nguyen Thi Hong ', N'Nu   ', CAST(N'2000-10-18' AS Date), N'073435463', N'Nghi viec', N'Nghe An', 0)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1011    ', N'Vo Van Hai', N'Nam  ', CAST(N'2000-07-13' AS Date), N'0315612345', N'Nhan Vien', N'Ha Tinh', 10000000)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1012    ', N'Dang thi thuong', N'Nam  ', CAST(N'2021-04-09' AS Date), N'1235689086', N'Nghi viec', N'dong da', 0)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1013    ', N'dang thi thuong', N'Nam  ', CAST(N'2021-04-09' AS Date), N'234567890', N'nhan vien', N'dong da', 23456)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1014    ', N'Le Quang Long', N'Nam  ', CAST(N'2021-04-09' AS Date), N'083200987', N'Nghi viec', N'Dong Da', 0)
GO
INSERT [dbo].[NHAN_VIEN] ([ID_NV], [TEN_NV], [GIOI_TINH], [NGAY_SINH], [SDT], [CHUC_VU], [DIA_CHI], [LUONG]) VALUES (N'NV1015    ', N'Le Quang Long', N'Nam  ', CAST(N'2021-04-09' AS Date), N'0932008663', N'Nghi viec', N'Dong Da', 0)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PN1001    ', 10, 2.5, 25)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PN1004    ', 10, 2.5, 25)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PN1011    ', 10, 2.5, 25)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PN1002    ', 10, 10.5, 105)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PN1003    ', 10, 10.5, 105)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PN1004    ', 8, 10.5, 84)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PN1005    ', 5, 10.5, 52.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PN1006    ', 5, 10.5, 52.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PN1007    ', 5, 10.5, 52.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PN1003    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PN1004    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PN1005    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PN1006    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PN1007    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PN1008    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PN1003    ', 2, 80.5, 161)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PN1006    ', 2, 80.5, 161)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PN1007    ', 2, 80.5, 161)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PN1008    ', 2, 80.5, 161)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PN1010    ', 2, 80.5, 241.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PN1008    ', 3, 20.5, 61.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PN1011    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PN1001    ', 5, 150, 750)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PN1010    ', 3, 150.5, 451.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1007    ', N'PN1001    ', 5, 50, 250)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1007    ', N'PN1002    ', 3, 80.5, 241.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1007    ', N'PN1010    ', 3, 80.5, 241.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1008    ', N'PN1001    ', 3, 9, 27)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1008    ', N'PN1002    ', 3, 3.5, 10.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1008    ', N'PN1003    ', 3, 3.5, 10.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1009    ', N'PN1002    ', 3, 2.5, 7.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1009    ', N'PN1003    ', 3, 2.5, 7.5)
GO
INSERT [dbo].[NHAP_NL] ([ID_NL], [ID_NHAP], [SOLUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1009    ', N'PN1004    ', 3, 2.5, 7.5)
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1001    ', CAST(N'2021-06-10' AS Date), 127.5, N'NCC1004   ', N'NV1003    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1002    ', CAST(N'2021-06-20' AS Date), 127.5, N'NCC1002   ', N'NV1003    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1003    ', CAST(N'2021-06-30' AS Date), 127.5, N'NCC1003   ', N'NV1004    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1004    ', CAST(N'2021-07-10' AS Date), 127.5, N'NCC1003   ', N'NV1007    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1005    ', CAST(N'2021-07-20' AS Date), 127.5, N'NCC1001   ', N'NV1002    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1006    ', CAST(N'2021-07-30' AS Date), 127.5, N'NCC1005   ', N'NV1002    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1007    ', CAST(N'2021-08-10' AS Date), 127.5, N'NCC1002   ', N'NV1003    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1008    ', CAST(N'2021-08-20' AS Date), 127.5, N'NCC1007   ', N'NV1009    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1010    ', CAST(N'2021-09-10' AS Date), 127.5, N'NCC1001   ', N'NV1002    ')
GO
INSERT [dbo].[PHIEU_NHAP] ([ID_NHAP], [NGAY_NHAP], [TONG_TIEN], [ID_NHACC], [ID_NV]) VALUES (N'PN1011    ', CAST(N'2021-09-20' AS Date), 127.5, N'NCC1002   ', N'NV1002    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1001    ', CAST(N'2021-05-03' AS Date), 3637.5, N'NV1003    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1002    ', CAST(N'2021-06-20' AS Date), 2047.5, N'NV1004    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1003    ', CAST(N'2021-06-30' AS Date), 2285, N'NV1004    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1004    ', CAST(N'2021-07-10' AS Date), 1520, N'NV1003    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1005    ', CAST(N'2021-07-20' AS Date), 720, N'NV1003    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1006    ', CAST(N'2021-07-30' AS Date), 2020, N'NV1004    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1007    ', CAST(N'2021-08-10' AS Date), 1162.5, N'NV1004    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1008    ', CAST(N'2021-08-20' AS Date), 2567.5, N'NV1003    ')
GO
INSERT [dbo].[PHIEU_XUAT] ([ID_XUAT], [NGAY_XUAT], [TONG_TIEN], [ID_NV]) VALUES (N'PX1009    ', CAST(N'2021-08-30' AS Date), 1005, N'NV1003    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1001   ', CAST(N'2021-06-10' AS Date), N'Da Thanh Toan', N'KH1002    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1002   ', CAST(N'2021-06-20' AS Date), N'Da Thanh Toan', N'KH1003    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1003   ', CAST(N'2021-06-30' AS Date), N'Da Thanh Toan', N'KH1001    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1004   ', CAST(N'2021-07-10' AS Date), N'Da Thanh Toan', N'KH1009    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1005   ', CAST(N'2021-07-20' AS Date), N'Da Thanh Toan', N'KH1007    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1006   ', CAST(N'2021-07-30' AS Date), N'Da Thanh Toan', N'KH1004    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1007   ', CAST(N'2021-08-10' AS Date), N'Da Thanh Toan', N'KH1005    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1009   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1010    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1010   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1013    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1011   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1006    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1012   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1011    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1015   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1015    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1016   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1028    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1017   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1029    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1018   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1030    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1019   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1032    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1020   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1033    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1021   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1034    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1022   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1035    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1023   ', CAST(N'2021-05-03' AS Date), N'Da Thanh Toan', N'KH1036    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1024   ', CAST(N'2021-05-03' AS Date), N'Chua Thanh Toan', N'KH1028    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1025   ', CAST(N'2021-05-03' AS Date), N'Chua Thanh Toan', N'KH1037    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1026   ', CAST(N'2021-05-03' AS Date), N'Chua Thanh Toan', N'KH1038    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1027   ', CAST(N'2021-05-03' AS Date), N'Chua Thanh Toan', N'KH1028    ')
GO
INSERT [dbo].[PHIEU_YC] ([ID_PHIEU], [NGAY], [TRANG_THAI], [ID_KH]) VALUES (N'PYC1028   ', CAST(N'2021-03-02' AS Date), N'Chua Thanh Toan', N'KH1039    ')
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PX1001    ', 200, 3, 500)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PX1002    ', 30, 2.5, 75)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PX1003    ', 120, 2.5, 300)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PX1004    ', 120, 2.5, 300)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1001    ', N'PX1009    ', 200, 2.5, 500)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PX1001    ', 10, 10.5, 105)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PX1002    ', 20, 10.5, 210)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PX1003    ', 10, 10.5, 105)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PX1004    ', 20, 10.5, 210)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PX1005    ', 10, 10.5, 105)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1002    ', N'PX1006    ', 10, 10.5, 105)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PX1003    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PX1005    ', 20, 20.5, 410)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PX1006    ', 10, 20.5, 205)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PX1007    ', 20, 20.5, 410)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PX1008    ', 10, 20.5, 205)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1003    ', N'PX1009    ', 5, 20.5, 102.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PX1001    ', 5, 80.5, 402.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PX1002    ', 10, 80.5, 805)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PX1004    ', 10, 80.5, 805)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PX1008    ', 20, 80.5, 1610)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1004    ', N'PX1009    ', 5, 80.5, 402.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PX1001    ', 50, 20.5, 1025)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PX1002    ', 10, 20.5, 205)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PX1003    ', 50, 20.5, 1025)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PX1004    ', 10, 20.5, 205)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PX1005    ', 10, 20.5, 205)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1005    ', N'PX1006    ', 10, 20.5, 205)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PX1001    ', 10, 150.5, 1505)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PX1002    ', 5, 150.5, 752.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PX1003    ', 5, 150.5, 752.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PX1006    ', 10, 150.5, 1505)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PX1007    ', 5, 150.5, 752.5)
GO
INSERT [dbo].[XUAT_NL] ([ID_NL], [ID_XUAT], [SO_LUONG], [DON_GIA], [TONG_GIA]) VALUES (N'NL1006    ', N'PX1008    ', 5, 150.5, 752.5)
GO
ALTER TABLE [dbo].[BAN]  WITH CHECK ADD  CONSTRAINT [PK_PC] FOREIGN KEY([ID_PHIEU])
REFERENCES [dbo].[PHIEU_YC] ([ID_PHIEU])
GO
ALTER TABLE [dbo].[BAN] CHECK CONSTRAINT [PK_PC]
GO
ALTER TABLE [dbo].[DANGNHAP]  WITH CHECK ADD FOREIGN KEY([ID_NV])
REFERENCES [dbo].[NHAN_VIEN] ([ID_NV])
GO
ALTER TABLE [dbo].[GOI_MON]  WITH CHECK ADD FOREIGN KEY([ID_MONAN])
REFERENCES [dbo].[MON_AN] ([ID_MONAN])
GO
ALTER TABLE [dbo].[GOI_MON]  WITH CHECK ADD FOREIGN KEY([ID_PHIEU])
REFERENCES [dbo].[PHIEU_YC] ([ID_PHIEU])
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [PK_KM] FOREIGN KEY([ID_KM])
REFERENCES [dbo].[KHUYEN_MAI] ([ID_KM])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [PK_KM]
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [PK_NVT] FOREIGN KEY([ID_NV])
REFERENCES [dbo].[NHAN_VIEN] ([ID_NV])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [PK_NVT]
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [PK_YC] FOREIGN KEY([ID_PHIEU])
REFERENCES [dbo].[PHIEU_YC] ([ID_PHIEU])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [PK_YC]
GO
ALTER TABLE [dbo].[MON_AN]  WITH CHECK ADD  CONSTRAINT [PK_LM] FOREIGN KEY([ID_LOAIMON])
REFERENCES [dbo].[LOAI_MON] ([ID_LOAIMON])
GO
ALTER TABLE [dbo].[MON_AN] CHECK CONSTRAINT [PK_LM]
GO
ALTER TABLE [dbo].[NHAP_NL]  WITH CHECK ADD FOREIGN KEY([ID_NHAP])
REFERENCES [dbo].[PHIEU_NHAP] ([ID_NHAP])
GO
ALTER TABLE [dbo].[NHAP_NL]  WITH CHECK ADD FOREIGN KEY([ID_NL])
REFERENCES [dbo].[NGUYEN_LIEU] ([ID_NL])
GO
ALTER TABLE [dbo].[PHIEU_NHAP]  WITH CHECK ADD FOREIGN KEY([ID_NV])
REFERENCES [dbo].[NHAN_VIEN] ([ID_NV])
GO
ALTER TABLE [dbo].[PHIEU_NHAP]  WITH CHECK ADD  CONSTRAINT [PK_CC] FOREIGN KEY([ID_NHACC])
REFERENCES [dbo].[NHA_CC] ([ID_NHACC])
GO
ALTER TABLE [dbo].[PHIEU_NHAP] CHECK CONSTRAINT [PK_CC]
GO
ALTER TABLE [dbo].[PHIEU_NHAP]  WITH CHECK ADD  CONSTRAINT [PK_NV] FOREIGN KEY([ID_NV])
REFERENCES [dbo].[NHAN_VIEN] ([ID_NV])
GO
ALTER TABLE [dbo].[PHIEU_NHAP] CHECK CONSTRAINT [PK_NV]
GO
ALTER TABLE [dbo].[PHIEU_XUAT]  WITH CHECK ADD FOREIGN KEY([ID_NV])
REFERENCES [dbo].[NHAN_VIEN] ([ID_NV])
GO
ALTER TABLE [dbo].[PHIEU_YC]  WITH CHECK ADD  CONSTRAINT [PK_KH] FOREIGN KEY([ID_KH])
REFERENCES [dbo].[KHACH_HANG] ([ID_KH])
GO
ALTER TABLE [dbo].[PHIEU_YC] CHECK CONSTRAINT [PK_KH]
GO
ALTER TABLE [dbo].[XUAT_NL]  WITH CHECK ADD FOREIGN KEY([ID_NL])
REFERENCES [dbo].[NGUYEN_LIEU] ([ID_NL])
GO
ALTER TABLE [dbo].[XUAT_NL]  WITH CHECK ADD FOREIGN KEY([ID_XUAT])
REFERENCES [dbo].[PHIEU_XUAT] ([ID_XUAT])
GO
/****** Object:  StoredProcedure [dbo].[ADDDETAILINPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---ADDDETAILINPUT
CREATE PROC [dbo].[ADDDETAILINPUT]
	@TENNL varchar(20),
	@SOLUONG INT,
	@DONGIA FLOAT,
	@IDNHAP CHAR(10)
AS
BEGIN
	DECLARE @IDNL CHAR(10)
IF(NOT EXISTS (SELECT * FROM NGUYEN_LIEU WHERE TEN_NL = @TENNL ))
BEGIN
 SET @IDNL =  DBO.NEW_ID_NL();
 INSERT INTO NGUYEN_LIEU(ID_NL, TEN_NL, SO_LUONG) VALUES (@IDNL, @TENNL, 0)
END;
ELSE BEGIN
	SELECT @IDNL = ID_NL FROM NGUYEN_LIEU WHERE TEN_NL = @TENNL
END;
IF (NOT EXISTS (SELECT * FROM PHIEU_NHAP WHERE ID_NHAP = @IDNHAP ))
BEGIN
	insert into PHIEU_NHAP (ID_NHAP) VALUES (@IDNHAP)
	insert into NHAP_NL(ID_NL,ID_NHAP, SOLUONG, DON_GIA) 
values (@IDNL, @IDNHAP, @SOLUONG, @DONGIA)
END;
ELSE BEGIN
insert into NHAP_NL(ID_NL,ID_NHAP, SOLUONG, DON_GIA) 
values (@IDNL, @IDNHAP, @SOLUONG, @DONGIA)
END;
END
GO
/****** Object:  StoredProcedure [dbo].[ADDDETAILOUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--ADD DETAIL OUTPUT
CREATE PROC [dbo].[ADDDETAILOUTPUT]
	@TENNL varchar(20),
	@SOLUONG INT,
	@DONGIA FLOAT,
	@IDXUAT CHAR(10)
AS
BEGIN
	DECLARE @IDNL CHAR(10)
	SELECT @IDNL = ID_NL FROM NGUYEN_LIEU WHERE TEN_NL = @TENNL
IF(NOT EXISTS (SELECT * FROM PHIEU_XUAT WHERE ID_XUAT = @IDXUAT))
BEGIN
	insert into PHIEU_XUAT (ID_XUAT) VALUES (@IDXUAT)
	insert into XUAT_NL(ID_NL,ID_XUAT, SO_LUONG, DON_GIA) 
values (@IDNL, @IDXUAT, @SOLUONG, @DONGIA)
END;
ELSE BEGIN
insert into XUAT_NL(ID_NL,ID_XUAT, SO_LUONG, DON_GIA) 
values (@IDNL, @IDXUAT, @SOLUONG, @DONGIA)
END;
END
GO
/****** Object:  StoredProcedure [dbo].[CN_MK]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--THAY DOI MAT KHAU
CREATE PROC [dbo].[CN_MK]
@idnv char(10),
@mk varchar(20)
AS
BEGIN
	UPDATE DANGNHAP SET MK = @mk WHERE ID_NV = @idnv
END
GO
/****** Object:  StoredProcedure [dbo].[Delete1GoiMon]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[Delete1GoiMon](@TenMon nvarchar(50),@ID_PYC char(10))
as 
begin
delete from GOI_MON where exists (select * from MON_AN where MON_AN.ID_MONAN=GOI_MON.ID_MONAN AND MON_AN.TEN_MONAN LIKE @TenMon and GOI_MON.ID_PHIEU LIKE @ID_PYC)
end
GO
/****** Object:  StoredProcedure [dbo].[DeleteBan]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[DeleteBan](@ID_Ban char(10))
as 
begin
delete FROM dbo.BAN where ID_BAN LIKE @ID_Ban
end
GO
/****** Object:  StoredProcedure [dbo].[Get_PYC_T]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[Get_PYC_T]
as 
begin
SELECT ID_PHIEU,NGAY,TRANG_THAI,ID_KH FROM dbo.PHIEU_YC
end

GO
/****** Object:  StoredProcedure [dbo].[GetBanChuaDat]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[GetBanChuaDat] AS
begin
SELECT ID_BAN FROM dbo.BAN where TRANG_THAI LIKE 'Chua Dat%'
end
GO
/****** Object:  StoredProcedure [dbo].[GetMonAn]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[GetMonAn](@ID_PYC char(10)) AS
begin
SELECT TEN_MONAN,SOLUONG,DON_GIA FROM MON_AN,GOI_MON where MON_AN.ID_MONAN=GOI_MON.ID_MONAN AND GOI_MON.ID_PHIEU LIKE @ID_PYC
end
GO
/****** Object:  StoredProcedure [dbo].[GetSDT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[GetSDT] (@ID char(10)) AS
begin
SELECT SDT FROM dbo.KHACH_HANG where SDT LIKE @ID
end
GO
/****** Object:  StoredProcedure [dbo].[INPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--THEM VA SUA INPUT
CREATE PROC [dbo].[INPUT]
	@ID_NHAP char(10),
	@NV VARchar(20),
	@TENCC VARCHAR(20),
	@TONG_TIEN FLOAT,
	@NGAY_NHAP DATE
AS
BEGIN
DECLARE @ID_NCC VARCHAR(20)
DECLARE @ID_NV VARCHAR(20)
SELECT @ID_NCC= ID_NHACC FROM NHA_CC WHERE NHACC = @TENCC 
SELECT @ID_NV= ID_NV FROM NHAN_VIEN WHERE TEN_NV = @NV 
IF(NOT EXISTS (SELECT * FROM PHIEU_NHAP WHERE ID_NHAP=@ID_NHAP))
BEGIN
	insert into PHIEU_NHAP(ID_NHAP, NGAY_NHAP, TONG_TIEN, ID_NHACC,ID_NV)
values (@ID_NHAP, @NGAY_NHAP, @TONG_TIEN, @ID_NCC, @ID_NV)
END;
ELSE BEGIN
	UPDATE PHIEU_NHAP SET ID_NV = @ID_NV, ID_NHACC = @ID_NCC, TONG_TIEN = @TONG_TIEN, NGAY_NHAP = @NGAY_NHAP WHERE ID_NHAP = @ID_NHAP
END;
END
GO
/****** Object:  StoredProcedure [dbo].[INSERT_UPDATE_MONAN]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[INSERT_UPDATE_MONAN](@ID_MONAN CHAR(10),@TEN_MONAN NVARCHAR(50),@DON_GIA FLOAT,@ID_LOAIMON CHAR(10))
AS
BEGIN
IF @ID_MONAN = ANY(SELECT ID_MONAN FROM dbo.MON_AN)
BEGIN
UPDATE dbo.MON_AN
SET TEN_MONAN = @TEN_MONAN,DON_GIA = @DON_GIA,ID_LOAIMON = @ID_LOAIMON
WHERE ID_MONAN = @ID_MONAN
END
ELSE
BEGIN
INSERT INTO dbo.MON_AN
(ID_MONAN,TEN_MONAN,DON_GIA,ID_LOAIMON)
VALUES(@ID_MONAN,@TEN_MONAN, @DON_GIA,@ID_LOAIMON)
END
END
GO
/****** Object:  StoredProcedure [dbo].[InsertBan]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[InsertBan](@ID_Ban char(10),@TrangThai nchar(20),@ID_PYC char(10))
as 
begin
insert BAN values( @ID_Ban,@TrangThai,6,@ID_PYC)
end
GO
/****** Object:  StoredProcedure [dbo].[OUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--THEM SUA OUTPUT
CREATE PROC [dbo].[OUTPUT]
	@ID_XUAT char(10),
	@NV VARchar(20),
	@TONG_TIEN FLOAT,
	@NGAY_XUAT DATE
AS
BEGIN
DECLARE @ID_NV VARCHAR(20)
SELECT  @ID_NV=ID_NV FROM NHAN_VIEN WHERE TEN_NV = @NV
IF(NOT EXISTS(SELECT * FROM PHIEU_XUAT WHERE ID_XUAT=@ID_XUAT))
BEGIN
	insert into PHIEU_XUAT(ID_XUAT, NGAY_XUAT, TONG_TIEN,ID_NV)
values (@ID_XUAT, @NGAY_XUAT, @TONG_TIEN, @ID_NV)
END;
ELSE BEGIN
	UPDATE PHIEU_XUAT SET ID_NV = @ID_NV,  TONG_TIEN = @TONG_TIEN, NGAY_XUAT = @NGAY_XUAT WHERE ID_XUAT = @ID_XUAT
END;
END
GO
/****** Object:  StoredProcedure [dbo].[proc_Login]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[proc_Login]
@ID nvarchar(50),
@MK nvarchar(50)
as
begin
	select * from DANGNHAP where ID_NV = @ID AND MK = @MK
	end
GO
/****** Object:  StoredProcedure [dbo].[PS_DETAILINPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 --SUA DETAILINPUT
 CREATE PROC [dbo].[PS_DETAILINPUT]
	@TENNL varchar(20),
	@SOLUONG INT,
	@DONGIA FLOAT,
	@IDNHAP CHAR(10)
AS
BEGIN
	UPDATE NHAP_NL SET SOLUONG = @soluong, DON_GIA = @dongia WHERE ID_NHAP = @idnhap AND ID_NL IN (SELECT ID_NL FROM NGUYEN_LIEU WHERE TEN_NL = @tennl)
END
GO
/****** Object:  StoredProcedure [dbo].[PS_DETAILOUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--SUA DETAIL UOTPUT
CREATE PROC [dbo].[PS_DETAILOUTPUT]
	@TENNL varchar(20),
	@SOLUONG INT,
	@DONGIA FLOAT,
	@IDXUAT CHAR(10)
AS
BEGIN
	UPDATE XUAT_NL SET SO_LUONG = @soluong, DON_GIA = @dongia WHERE ID_XUAT = @idxuat AND ID_NL IN (SELECT ID_NL FROM NGUYEN_LIEU WHERE TEN_NL = @tennl)
END
GO
/****** Object:  StoredProcedure [dbo].[PS_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--sua khach hang
CREATE PROC [dbo].[PS_KH]
@idkh char(10),
@tenkh varchar(30),
@sdt varchar(20),
@gioitinh varchar(10),
@diachi varchar(20)
AS
BEGIN
	UPDATE KHACH_HANG SET TEN_KH = @tenkh, SDT = @sdt, GIOI_TINH = @gioitinh, DIA_CHI = @diachi WHERE ID_KH = @idkh	
END
GO
/****** Object:  StoredProcedure [dbo].[PS_NCC]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PS_NCC]
	@ID varchar(20),
	@NCC varchar(30),
	@SDT varchar(20),
	@DC varCHAR(30)
AS
BEGIN
IF(NOT EXISTS (SELECT * FROM NHA_CC WHERE ID_NHACC=@ID))
BEGIN
	
	insert into NHA_CC(ID_NHACC,NHACC, SDT, DIA_CHI) 
values (@ID, @NCC, @SDT, @DC)
END;
ELSE BEGIN
 UPDATE NHA_CC SET NHACC = @NCC, SDT = @SDT, DIA_CHI = @DC WHERE ID_NHACC = @NCC
END;
END
GO
/****** Object:  StoredProcedure [dbo].[PS_NV]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--sua nhan vien
CREATE PROC [dbo].[PS_NV]
@idnv char(10),
@tennv varchar(30),
@gioitinh varchar(10),
@ngaysinh DATE,
@sdt varchar(20),
@chucvu VARCHAR(10),
@diachi varchar(20),
@luong FLOAT
AS
BEGIN
	UPDATE NHAN_VIEN SET TEN_NV = @tennv,GIOI_TINH = @gioitinh, NGAY_SINH = @ngaysinh, SDT = @sdt, CHUC_VU = @chucvu,  DIA_CHI = @diachi, LUONG = @luong WHERE ID_NV = @idnv
END
GO
/****** Object:  StoredProcedure [dbo].[PT_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--THEM
CREATE PROC [dbo].[PT_KH]
@idkh char(10),
@tenkh varchar(30),
@sdt varchar(20),
@gioitinh varchar(10),
@diachi varchar(20)
AS
BEGIN
	INSERT INTO KHACH_HANG(ID_KH,TEN_KH, SDT, GIOI_TINH, DIA_CHI) VALUES(@idkh, @tenkh, @sdt, @gioitinh, @diachi)
	
END
GO
/****** Object:  StoredProcedure [dbo].[PT_NV]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--THEM
CREATE PROC [dbo].[PT_NV]
@idnv char(10),
@tennv Nvarchar(30),
@gioitinh varchar(10),
@ngaysinh DATE,
@sdt Nvarchar(20),
@chucvu NVARCHAR(10),
@diachi Nvarchar(20),
@luong FLOAT
AS
BEGIN
	INSERT INTO NHAN_VIEN(ID_NV,TEN_NV, GIOI_TINH,NGAY_SINH, SDT, CHUC_VU, DIA_CHI, LUONG) VALUES(@idnv, @tennv, @gioitinh, @ngaysinh,@sdt,@chucvu, @diachi, @luong)
	
END
GO
/****** Object:  StoredProcedure [dbo].[PX_DETAILINPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--XOA DETAILINPUT
 CREATE PROC [dbo].[PX_DETAILINPUT]
	@TENNL varchar(20),
	@IDNHAP CHAR(10)
AS
BEGIN
	DELETE NHAP_NL WHERE ID_NHAP = @idnhap AND ID_NL IN (SELECT ID_NL FROM NGUYEN_LIEU WHERE TEN_NL = @tennl)
END
GO
/****** Object:  StoredProcedure [dbo].[PX_DETAILOUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--XOA DETAILOUTPUT
 CREATE PROC [dbo].[PX_DETAILOUTPUT]
	@TENNL varchar(20),
	@IDXUAT CHAR(10)
AS
BEGIN
	DELETE XUAT_NL WHERE ID_XUAT = @idxuat AND ID_NL IN (SELECT ID_NL FROM NGUYEN_LIEU WHERE TEN_NL = @tennl)
END
GO
/****** Object:  StoredProcedure [dbo].[PX_INPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--XOA INPUT
CREATE PROC [dbo].[PX_INPUT]
@ID_NHAP char(10)
AS
BEGIN
	DELETE NHAP_NL WHERE ID_NHAP = @ID_NHAP
	DELETE PHIEU_NHAP WHERE ID_NHAP = @ID_NHAP
END
GO
/****** Object:  StoredProcedure [dbo].[PX_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Xoa khach hang
CREATE PROC [dbo].[PX_KH]
@idkh char(10)
AS
BEGIN
	UPDATE KHACH_HANG SET TEN_KH = '', SDT = '', GIOI_TINH = '', DIA_CHI = '' WHERE ID_KH = @idkh

END
GO
/****** Object:  StoredProcedure [dbo].[PX_NV]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Xoa nhan vien
CREATE PROC [dbo].[PX_NV]
@idnv char(10)
AS
BEGIN
	DELETE DANGNHAP WHERE ID_NV = @idnv
	UPDATE NHAN_VIEN SET  CHUC_VU = N'Nghi viec', LUONG = 0 WHERE ID_NV = @idnv
END
GO
/****** Object:  StoredProcedure [dbo].[PX_OUTPUT]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--XOA OUTPUT
CREATE PROC [dbo].[PX_OUTPUT]
@ID_XUAT char(10)
AS
BEGIN
	DELETE XUAT_NL WHERE ID_XUAT = @ID_XUAT
	DELETE PHIEU_XUAT WHERE ID_XUAT = @ID_XUAT
END
GO
/****** Object:  StoredProcedure [dbo].[Update_Ban_Null]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[Update_Ban_Null](@ID_PYC char(10)) AS
begin
update BAN set TRANG_THAI ='Chua Dat' , ID_PHIEU=null where ID_PHIEU like @ID_PYC
end

GO
/****** Object:  StoredProcedure [dbo].[UpdateSDT_KH]    Script Date: 2021-12-20 4:55:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[UpdateSDT_KH](@ID_KH char(10),@sdt varchar(12))
as 
begin
update KHACH_HANG SET SDT = @sdt  where ID_KH LIKE @ID_KH
end




GO
